MediArchive/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appointment/', include('appointment.urls')),
    url(r'^', include('appointment.urls')),
    url(r'^lab/', include('lab.urls')),
    url(r'^', include('lab.urls')),
    url(r'^surgery/', include('surgery.urls')),
    url(r'^', include('surgery.urls')),
    url(r'^doctor/', include('doctor.urls')),
    url(r'^', include('doctor.urls')),

]

appointment/urls.py
from django.conf.urls import url
from . import views

app_name =  'appointment'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<appointment_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<consultation_id>[0-9]+)/isdoctor/$', views.isdoctor, name='isdoctor'),
    url(r'^consultations/(?P<filter_by>[a-zA_Z]+)/$', views.consultations, name='consultations'),
    url(r'^create_appointment/$', views.create_appointment, name='create_appointment'),
    url(r'^(?P<appointment_id>[0-9]+)/create_consultation/$', views.create_consultation, name='create_consultation'),
    url(r'^(?P<appointment_id>[0-9]+)/delete_consultation/(?P<consultation_id>[0-9]+)/$', views.delete_consultation, name='delete_consultation'),
    url(r'^(?P<appointment_id>[0-9]+)/favorite_appointment/$', views.favorite_appointment, name='favorite_appointment'),
    url(r'^(?P<appointment_id>[0-9]+)/delete_appointment/$', views.delete_appointment, name='delete_appointment'),
]

appointment/models.py
from django.db import models
from django.contrib.auth.models import Permission, User



class Profile(models.Model):
    user=models.ForeignKey(User,default=1)
    aadhar_no=models.CharField(max_length=16)
    def __str__(self):
        return self.user.username

# Create your models here.
class Appointment(models.Model):
    user = models.ForeignKey(User, default=1)
    date = models.CharField(max_length=20)
    patient_name = models.CharField(max_length=250)
    doctor = models.CharField(max_length=250)
    time = models.CharField(max_length=250)
    file_number = models.CharField(max_length=20)
    is_doctor = models.BooleanField(default=False)

    def __str__(self):
        return self.doctor + '-' + self.patient_name

class Consultation(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    consultation_number = models.CharField(max_length=250)
    doctor_name = models.CharField(max_length=250)
    patient_name = models.CharField(max_length=250)
    file_number = models.CharField(max_length=20)
    is_doctor = models.BooleanField(default=False)

    def __str__(self):
        return self.doctor_name + '-' + self.patient_name

appointment/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import Appointment, Consultation


class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ['date', 'patient_name', 'doctor', 'time', 'file_number', 'is_doctor']


class ConsultationForm(forms.ModelForm):

    class Meta:
        model = Consultation
        fields = ['consultation_number', 'doctor_name','patient_name', 'file_number', 'is_doctor']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

appointment/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import AppointmentForm, ConsultationForm, UserForm
from .models import Appointment, Consultation


def create_appointment(request):
    if not request.user.is_authenticated():
        return render(request, 'appointment/login.html')
    else:
        form = AppointmentForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.user = request.user
            appointment.doctor = request.user
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'appointment': appointment,
                    'form': form,
                }
                return render(request, 'appointment/create_appointment.html', context)
            appointment.save()
            return render(request, 'appointment/detail.html', {'appointment': appointment})
        context = {
            "form": form,
        }
        return render(request, 'appointment/create_appointment.html', context)


def create_consultation(request, appointment_id):
    form = ConsultationForm(request.POST or None, request.FILES or None)
    appointment  = get_object_or_404(Appointment, pk=appointment_id)
    if form.is_valid():
        appointments_consultations = appointment.consultation_set.all()
        for c in appointments_consultations:
            if c.doctor == form.cleaned_data.get("doctor"):
                context = {
                    'appointment': appointment,
                    'form': form,
                    'error_message': 'You already added that appointment',
                }
                return render(request, 'appointment/create_consultation.html', context)
        consultation = form.save(commit=False)
        consultation.appointment = appointment
        consultation.save()
        return render(request, 'appointment/detail.html', {'appointment': appointment})
    context = {
        'appointment': appointment,
        'form': form,
    }
    return render(request, 'appointment/create_consultation.html', context)


def delete_appointment(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    appointment.delete()
    appointment = Appointment.objects.filter(user=request.user)
    return render(request, 'appointment/index.html', {'appointment': appointment})


def delete_consultation(request, appointment_id, consultation_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    consultation = Consultation.objects.get(pk=consultation_id)
    consultation.delete()
    return render(request, 'appointment/detail.html', {'appointment': appointment})


def detail(request, appointment_id):
    if not request.user.is_authenticated():
        return render(request, 'appointment/login.html')
    else:
        user = request.user
        appointment = get_object_or_404(Appointment, pk=appointment_id)
        return render(request, 'appointment/detail.html', {'appointment': appointment, 'user': user})


def isdoctor(request, consultation_id):
    consultation = get_object_or_404(Consultation, pk=consultation_id)
    try:
        if consultation.is_doctor:
            consultation.is_doctor = False
        else:
            consultation.is_doctor = True
        consultation.save()
    except (KeyError, Consultation.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    try:
        if appointment.is_doctor:
            appointment.is_doctor = False
        else:
            appointment.is_doctor = True
        appointment.save()
    except (KeyError, Appointment.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'appointment/login.html')
    else:
        appointments = Appointment.objects.filter(user=request.user)
        consultation_results = Consultation.objects.all()
        query = request.GET.get("q")
        if query:
            appointments = appointments.filter(
                Q(doctor__icontains=query) |
                Q(patient_name__icontains=query)
            ).distinct()
            consultation_results = consultation_results.filter(
                Q(doctor__icontains=query)
            ).distinct()
            return render(request, 'appointment/index.html', {
                'appointments': appointments,
                'consultations': consultation_results,
            })
        else:
            return render(request, 'appointment/index.html', {'appointments': appointments})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'appointment/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                appointments = Appointment.objects.filter(user=request.user)
                return render(request, 'appointment/index.html', {'appointments': appointments})
            else:
                return render(request, 'appointment/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'appointment/login.html', {'error_message': 'Invalid login'})
    return render(request, 'appointment/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                appointments = Appointment.objects.filter(user=request.user)
                return render(request, 'appointment/index.html', {'appointments': appointments})
    context = {
        "form": form,
    }
    return render(request, 'appointment/register.html', context)


def consultations(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'appointment/login.html')
    else:
        try:
            consultation_ids = []
            for appointment in Appointment.objects.filter(user=request.user):
                for consultation in appointment.consultation_set.all():
                    consultation_ids.append(consultation.pk)
            users_consultations = Consultation.objects.filter(pk__in=consultation_ids)
            if filter_by == 'doctor':
                users_consultations = users_consultations.filter(is_favorite=True)
        except Appointment.DoesNotExist:
            users_consultations = []
        return render(request, 'appointment/consultations.html', {
            'consultation_list': users_consultations,
            'filter_by': filter_by,
        })

appointment/templates/appointment/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Medi-Archive{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'appointment/style.css' %}"/>
    <script src="hsttps://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'appointment/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'appointment:index' %}">Medi-Archive</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block appointments_active %}{% endblock %}"><a href="{% url 'appointment:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Appointments</a></li>
                <li class="{% block consultations_active %}{% endblock %}"><a href="{% url 'appointment:consultations' 'all' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Consultations</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'appointment:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'appointment:create_appointment' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Appointment
                    </a>
                </li>
                <li>
                    <a href="{% url 'appointment:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

appointment/templates/appointment/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MediArchive{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'appointment/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'appointment/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'appointment:index' %}">Medi-Archive</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'appointment:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'appointment:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>


appointment/templates/appointment/consultations.html
{% extends 'appointment/base.html' %}
{% block title %}{{ Consultations }}{% endblock %}
{% block consultations_active %}active{% endblock %}

{% block body %}
<div class="container-fluid consultations-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == all %}class="active"{% endif %}><a href="{% url 'appointment:consultations' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == doctor %}class="active"{% endif %}><a href="{% url 'appointment:consultations' 'doctor' %}">Regular Doctor</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Consultation_number</th>
                                <th>Doctor</th>
                                <th>Patient_name</th>
                                <th>File Number</th>
                                <th>Regular Doctor?</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for consultation in consultation_list %}
                                <tr>
                                    <td>{{ consultation.consultation_number }}</td>
                                    <td>{{ consultation.doctor }}</td>
                                    <td>{{ consultation.patient_name }}</td>
                                    <td>{{ consultation.is_doctor }}</td>
                                    <td>{{ consultation.appointment.doctor }}</td>

                                        <a href="{% url 'appointment:isdoctor' consultation.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if consultation.isdoctor %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

appointment/templates/appointment/create_consultation.html
{% extends 'appointment/base.html' %}
{% block title %}Add a New Consultation{% endblock %}
{% block appointments_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Appointment Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'appointment:detail' appointment.id %}">
                           <img src="../../static/images/hospital.jpg" class="img-responsive">
                        </a>
                    <h1>{{ appointment.doctor }} <small>{{ appointment.is_doctor }}</small></h1>
                    <h2>{{ appointment.patient_name }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Consultation Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'appointment:detail' appointment.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'appointment:create_consultation' appointment.id %}">Add New Consultation</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Consultation</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="appointment" value="{{ appointment }}">
                        {% include 'appointment/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}



appointment/templates/appointment/detail.html
{% extends 'appointment/base.html' %}
{% block title %}{{ Appointment }}{% endblock %}
{% block appointments_active %}active{% endblock %}

{% block body %}
<div class="container-fluid consultations-container">

    <div class="row">

        <!-- Left Appointment Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'appointment:detail' appointment.id %}">
                        <img src="../../static/images/hospital.jpg" class="img-responsive">
                    </a>
                    <h1>{{ appointment.doctor }} <small>{{ appointment.is_doctor }}</small></h1>
                    <h2>{{ appointment.patient_name }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Consultation Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'appointment:detail' appointment.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'appointment:create_consultation' appointment.id %}">Add New Consultation</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Consultations</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Time</th>
                            <th>Date</th>
                            <th>File Number</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for consultation in appointment.consultation_set.all %}
                            <tr>
                                <td>{{ appointment.time }}</td>
                                <td>{{ appointment.date }}</td>
                                <td>{{ appointment.file_number }}</td>
                                <td>
                                    <a href="{% url 'appointment:isdoctor' consultation.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if consultation.isdoctor %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'appointment:delete_consultation' appointment.id consultation.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="consultation_id" value="{{ consultation.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}























appointment/templates/appointment/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"> {{field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{%endfor %}

appointment/templates/appointment/index.html
{% extends 'appointment/base.html' %}
{% block title %}All Appointments{% endblock %}
{% block appointments_active %} active {% endblock %}

{% block body %}
 <div class="appointments-container container-fluid">

     <!--Appointments-->
     <div class="row">
         <div class="col-sm-12">
             <h3> Welcome {{ user.username }}. Here are the appointments for today.</h3>
         </div>

         {% if appointments %}
           {% for appointments in appointment %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'appointment:detail' appointment.id %}">
                            <img src="../../static/images/hospital.jpg" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h4> {{ appointment.doctor }}</h4>

                            <!--View Details -->
                            <a href="{% url 'appointment:detail' appointment.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Appointment -->
                            <form action="{% url 'appointment:appointment_delete' appointment.id %}" method="post" style="display: inline;">

                                {% csrf_token %}
                                <input type="hidden" name="appointment_id" value="{{ appointment.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
         {% else %}
         <div class="col-sm-12">
             <br>
             <a href="{% url 'appointment:create_appointment' %}">
                 <button type="button" class="btn btn-success">
                     <span class="glyphicon glyphicon-plus"></span>&nbsp; Add An Appointment
                 </button>
             </a>
         </div>
      {% endif %}
  </div>

     <!-- Users searches and there are appointments -->
     {% if consultations %}
     <div class="row">
         <div class="col-sm-12">
             <h3> Consultation</h3>
         </div>
         <div class="col-sm-12">
             <div class="panel panel-default">
                 <div class="panel_body">
                     <table class="table">
                         <thead>
                                <tr>
                                    <th>Consultation Number</th>
                                    <th>Doctor</th>
                                    <th>Patient Name</th>
                                    <th>File number</th>
                                    <th>Regular doctor</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for consultation in consultations %}
                                    <tr>
                                        <td>{{ consultation.consultation_number }}</td>
                                        <td>{{ consultation.appointment.doctor }}</td>
                                        <td>{{ consultation.patient_name }}</td>
                                        <td>{{ consultation.file_number }}</td>
                                        <td>
                                            <a href="{% url 'appointment:isdoctor' consultation.id %}" class="btn-isdoctor"><span class="glyphicon glyphicon-star {% if consultation.is_doctor %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                     </table>
                 </div>
             </div>
         </div>
     </div>
   {% endif %}
 </div>
{% endblock %}



appointment/templates/appointment/login.html
{% extends 'appointment/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'appointment:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'appointment:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}